#!/bin/bash

SOURCE="/home/ubuntu/project"
S3_BUCKET="s3://wisecow11"
DATE=$(date +%Y-%m-%d_%H-%M-%S)
DEST="$S3_BUCKET/backup_$DATE"

aws s3 sync "$SOURCE" "$DEST" --delete

if [ $? -eq 0 ]; then
  echo "Backup completed"
  echo "Backup files at $DEST"
else
  echo "Backup failed!"
fi
